config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: "static_pages#contact"
  get '/random', to: "static_pages#random"
  get '/signup', to: "users#new"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  default_scope -> {order(:content)}
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 4}
  validate :valid_SCP

  def valid_SCP 
    errors.add(:base, 'Requires valid SCP number') unless self.content.match?(/[0-4]\d+[1-9]/)
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites, dependent: :destroy
    default_scope -> { order(:name) }
    before_save { self.email = email.downcase }

    validates :name, presence: true, length: {maximum: 50},
        uniqueness: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
        format: {with: VALID_EMAIL_REGEX},
        uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

	private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

    def create
        @favorite = current_user.favorites.build(favorite_params)
        if @favorite.save
          flash[:success] = "Favorite!"
          redirect_to current_user
        else
          render 'static_pages/home'
        end
    end
  
    def destroy
        @favorite.destroy
        flash[:success] = "Favorite deleted"
        redirect_to current_user
    end

    private

    def favorite_params
      params.require(:favorite).permit(:content)
    end

    def correct_user
        @favorite = current_user.favorites.find_by(id: params[:id])
        redirect_to root_url if @favorite.nil?
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @favorite = current_user.favorites.build\
    end
  end

  def about
  end

  def contact
  end

  def random
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @favorites = @user.favorites.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the BestCP!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def index 
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

      # Confirms the correct user.
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def get_num
        num = rand(1..4999)
        if (num < 10)
            num = "00" + num.to_s
        elsif (num < 100)
            num = "0" + num.to_s
        end
        return num
    end

    def to_num(num)
        num = num.to_i 
        if (num < 10)
            num = "00" + num.to_s
        elsif (num < 100)
            num = "0" + num.to_s
        end
        return num.to_s
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # Returns the current logged-in user (if any).
    def current_user
        if session[:user_id]
         @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
     !current_user.nil?
    end

    # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
   end
   
end

app/views/favorites/_favorite.html.erb
<li id="favorite-<%= favorite.id %>">
<% num = to_num(favorite.content) %>
  <span class="content"><a href="http://www.scpwiki.com/scp-<%= num %>">SCP-<%= num %></a></span>
  <span class="timestamp">
    Added <%= time_ago_in_words(favorite.created_at) %> ago.
    <% if current_user?(favorite.user) %>
    <%= link_to "delete", favorite, method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
  </span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
  BestCP, a favorites tracker for the <a href="http://scp-wiki.wikidot.com/">SCP Wiki.</a>
</small>
<nav>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #933">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Random SCP", random_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | BestCP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
     <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favorite_form.html.erb
<%= form_with(model: @favorite, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_field :content, placeholder: "Enter an SCP number (ex. 173)" %>
    </div>
    <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.favorites.count, "favorite") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
    <p>The SCP Wiki is an archive for short horror fiction on the internet.
    SCP stands for Special Containment Procedure, and each story describes
    a method for the containment of a fictional monster.
    The original SCP was <a href="http://scp-wiki.wikidot.com/scp-173">SCP-173</a>,
    The Sculpture, and one of the most famous is <a href="http://scp-wiki.wikidot.com/scp-682">SCP-682</a>,
    The Hard-To-Destroy Reptile. Start with these two if you're interested!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Me</h1>
    <p>I'm Erin Scherl, a senior student at Grinnell College. 
    This is my independent project for CSC 324.
    You can email me at scherler@grinnell.edu.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
<center>
<div class="center jumbotron">
  <h1>BestCP</h1>
  <p>Welcome to your home page! From here, you can add your favorite SCPs.
  Check your profile page to see all your favorites!</p>
</div>
</center>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="favorite_form">
        <%= render 'shared/favorite_form' %>
      </section>
    </aside>
  </div>
<% else %>
<div class="center jumbotron">
<center>
<h1>BestCP</h1>
    <p>This is a website to help you track your favorite entries on the <a href="http://scp-wiki.wikidot.com/">SCP Wiki.</a> 
        You can create an account to save your favorites,
        or log in if you already have one. Check the Random SCP page 
        or the About page for suggestions if you're new to SCPs.</p>
</center>
</div>
<% end %>

app/views/static_pages/random.html.erb
<% provide(:title, "Random") %>
<% num = get_num %>
<div class="center jumbotron">
<center>
    <h2>You should read:</h2>
    <h1><a href="http://www.scpwiki.com/scp-<%=num%>">SCP-<%=num%></a></h1>
    <div class="btn-group-vertical">
        <%= button_to "Get another suggestion", random_path, method: :get, class: "btn btn-default" %>
        <% if logged_in? %>
        <%= button_to "Add to favorites", favorites_path("favorite" => {"content"=> num}), method: :create, class: "btn btn-default" %>
        <% end %>
    </div>
</center>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
   <li>
     <%= gravatar_for user%>
     <%= link_to user.name, user %>
   </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
       <h1>
         <%= gravatar_for @user %>
         <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  <% if @user.favorites.any? %>
    <h3>Favorites (<%= @user.favorites.count %>)</h3>
    <ol class="favorites">
      <%= render @favorites %>
    </ol>
    <%= will_paginate @favorites %>
  <% end %>
</div>
</div>